services:
  mysql:
    image: mysql:8.0
    container_name: gsb2_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_gsb
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump-bd_gsb-202512101546.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: gsb2_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
